using System.Collections.Generic;

public struct Blocks
{
    public static readonly Dictionary<Enums.blockType, string> BlockType = new()
    {
        { Enums.blockType.empty, "emptyBlock"},
        { Enums.blockType.ground , "groundBlock"},
        { Enums.blockType.playerStart , "playerStartBlock"},
        { Enums.blockType.playerEnd , "playerEndBlock"},
        { Enums.blockType.box , "box"},
        { Enums.blockType.breakableBlock , "breakableBlock"},
        { Enums.blockType.chariot , "chariot"},
        { Enums.blockType.frog , "frog"},
        { Enums.blockType.ice , "ice"},
        { Enums.blockType.penguin , "penguin"},
        { Enums.blockType.rabbit , "rabbit"},
        { Enums.blockType.directionBlock, "ground8"},
        { Enums.blockType.panelStart, "panelStart"},
        { Enums.blockType.panelEnd, "panelEnd"},
        { Enums.blockType.M1_Block1, "M1_Block1"},
        { Enums.blockType.M1_Block2, "M1_Block2"},
        { Enums.blockType.M1_Block3, "M1_Block3"},
        { Enums.blockType.M1_Block4, "M1_Block4"},
        { Enums.blockType.M1_Block5, "M1_Block5"},
        { Enums.blockType.M1_Block6, "M1_Block6"},
        { Enums.blockType.M1_Block7, "M1_Block7"},
        { Enums.blockType.M1_Block8, "M1_Block8"},
        { Enums.blockType.M1_Block9, "M1_Block9"},
        { Enums.blockType.M1_Block10, "M1_Block10"},
        { Enums.blockType.M1_Block11, "M1_Block11"},
        { Enums.blockType.M1_Block12, "M1_Block12"},
        { Enums.blockType.M1_Block13, "M1_Block13"},
        { Enums.blockType.M1_Block14, "M1_Block14"},
        { Enums.blockType.M1_Block15, "M1_Block15"},
        { Enums.blockType.M1_Block16, "M1_Block16"},
        { Enums.blockType.M1_Block17, "M1_Block17"},
        { Enums.blockType.M1_Block18, "M1_Block18"},
        { Enums.blockType.M1_Border, "M1_Border"}
    };
    
    public static readonly Dictionary<string,Enums.blockType> BlockAdressType = new()
    {
        { "emptyBlock", Enums.blockType.empty},
        { "groundBlock", Enums.blockType.ground },
        { "playerStartBlock", Enums.blockType.playerStart},
        { "playerEndBlock", Enums.blockType.playerEnd},
        { "box", Enums.blockType.box},
        { "breakableBlock", Enums.blockType.breakableBlock},
        { "chariot", Enums.blockType.chariot},
        { "frog", Enums.blockType.frog},
        { "ice", Enums.blockType.ice},
        { "penguin", Enums.blockType.penguin},
        { "rabbit", Enums.blockType.rabbit},
        { "ground8", Enums.blockType.directionBlock},
        { "panelStart", Enums.blockType.panelStart},
        { "panelEnd", Enums.blockType.panelEnd},
        { "M1_Block1", Enums.blockType.M1_Block1},
        { "M1_Block2", Enums.blockType.M1_Block2},
        { "M1_Block3", Enums.blockType.M1_Block3},
        { "M1_Block4", Enums.blockType.M1_Block4},
        { "M1_Block5", Enums.blockType.M1_Block5},
        { "M1_Block6", Enums.blockType.M1_Block6},
        { "M1_Block7", Enums.blockType.M1_Block7},
        { "M1_Block8", Enums.blockType.M1_Block8},
        { "M1_Block9", Enums.blockType.M1_Block9},
        { "M1_Block10", Enums.blockType.M1_Block10},
        { "M1_Block11", Enums.blockType.M1_Block11},
        { "M1_Block12", Enums.blockType.M1_Block12},
        { "M1_Block13", Enums.blockType.M1_Block13},
        { "M1_Block14", Enums.blockType.M1_Block14},
        { "M1_Block15", Enums.blockType.M1_Block15},
        { "M1_Block16", Enums.blockType.M1_Block16},
        { "M1_Block17", Enums.blockType.M1_Block17},
        { "M1_Block18", Enums.blockType.M1_Block18},
        { "M1_Border", Enums.blockType.M1_Border}
    };
}
